# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: /
    weight: 1

  - parent: About Me
    name: Notifications
    url: notification
    weight: 110

  - parent: About Me
    name: News
    url: post
    weight: 120

  - name: Skills
    url: /
    weight: 2

  - parent: Skills
    name: Notifications
    url: notification
    weight: 610

  - parent: Skills
    name: News
    url: post
    weight: 620

  - name: Projcets
    url: /
    weight: 3

  - parent: Projcets
    name: Notifications
    url: notification
    weight: 610

  - parent: Projcets
    name: Notifications
    url: notification
    weight: 610

  - name: Certifications
    url: /
    weight: 4

  - parent: Certifications
    name: Notifications
    url: notification
    weight: 610

  - parent: Certifications
    name: Notifications
    url: notification
    weight: 610

  - name: Contact
    url: /
    weight: 5

  - parent: Contact
    name: Notifications
    url: notification
    weight: 610

  - parent: Contact
    name: Notifications
    url: notification
    weight: 610
