# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    identifier: aboutme
    url: /ko
    weight: 1

  - name: Skills
    identifier: skills
    url: /
    weight: 2

  - name: Projcets
    identifier: projects
    url: /
    weight: 3

  - name: Certifications
    identifier: certifi
    url: /
    weight: 4

  - name: Contact
    identifier: contact
    weight: 5

  - parent: contact
    name: Email
    url: /ko/contact
    weight: 6

  - parent: contact
    name: Social Media
    url: /
    weight: 7
