# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    identifier: aboutme
    url: /
    weight: 1

  - parent: aboutme
    name: Personal Info
    url: /
    weight: 110

  - parent: aboutme
    name: My Story
    url: /
    weight: 120

  - name: Skills
    identifier: skills
    url: /
    weight: 2

  - parent: skills
    name: Programming Languages
    url: /
    weight: 210

  - parent: skills
    name: Frameworks & Tools
    url: /
    weight: 220

  - name: Projcets
    identifier: projects
    url: /
    weight: 3

  - parent: projects
    name: Featured Projects
    url: /
    weight: 310

  - parent: projects
    name: Other Projects
    url: /
    weight: 320

  - name: Certifications
    identifier: certifi
    url: /
    weight: 4

  - parent: certifi
    name: Programming Certifications
    url: /
    weight: 410

  - parent: certifi
    name: Other Certifications
    url: /
    weight: 420

  - name: Contact
    identifier: contact
    url: /
    weight: 5

  - parent: contact
    name: Email
    url: contact
    weight: 510

  - parent: contact
    name: Social Media
    url: /
    weight: 520
