# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    url: /
    weight: 1

  - parent: About Me
    name: Personal Info
    url: /
    weight: 110

  - parent: About Me
    name: My Story
    url: /
    weight: 120

  - name: Skills
    url: /
    weight: 2

  - parent: Skills
    name: Programming Languages
    url: /
    weight: 210

  - parent: Skills
    name: Frameworks & Tools
    url: /
    weight: 220

  - name: Projcets
    url: /
    weight: 3

  - parent: Projcets
    name: Featured Projects
    url: /
    weight: 310

  - parent: Projcets
    name: Other Projects
    url: /
    weight: 320

  - name: Certifications
    url: /
    weight: 4

  - parent: Certifications
    name: Programming Certifications
    url: /
    weight: 410

  - parent: Certifications
    name: Other Certifications
    url: /
    weight: 420

  - name: Contact
    url: /
    weight: 5

  - parent: Contact
    name: Email
    url: /
    weight: 510

  - parent: Contact
    name: Social Media
    url: /
    weight: 520
